/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka.bank.avro;
@org.apache.avro.specific.AvroGenerated
public enum OperationType implements org.apache.avro.generic.GenericEnumSymbol<OperationType> {
  ACCEPT, PROCESSING, SUCCESS, FAIL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OperationType\",\"namespace\":\"kafka.bank.avro\",\"symbols\":[\"ACCEPT\",\"PROCESSING\",\"SUCCESS\",\"FAIL\"],\"default\":\"FAIL\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
